version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore src/Neo4jMapper.sln --source https://api.nuget.org/v3/index.json
build_script:
  - cmd: dotnet build src/Neo4jMapper.sln
test_script:
  - cmd: dotnet test src/UnitTests/UnitTests.csproj
