language: csharp
mono: none
dotnet: 2.1.300

install:
  - dotnet restore src/Neo4jMapper.sln --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/servicestack

script:
  - dotnet build src/Neo4jMapper.sln
  - dotnet test src/UnitTests/UnitTests.csproj
